### ISSUE TITLE
Add pythons specific gitignore

### ISSUE THREAD

**Issue by fluffybeing** [DOlearczyk/Tic-tac-toe#1]
Hi @DOlearczyk,

Your `.pyc` file has got pushed along with the project files. So, can you update your project with python specific `gitignore`. Here is the [link](https://github.com/github/gitignore/blob/master/Python.gitignore).

After updating your `.gitignore` file run these commands.

``` bash
git rm -r --cached .    # Remove cached files from git 
git add .                    # Add all the files from current project to git
git commit -m ".gitignore is now working"
git push -u origin master
```

**Comment by DOlearczyk** [comment]
Hello, @rahulrrixe

Thanks, fixed this issue.
